steps:
  - name: "node:10.15.1"
    id: "Yarn Install"
    args: ["yarn", "install"]
    env:
      - NODE_ENV=development

  - name: "node:10.15.1"
    id: "Running unit tests"
    args: ["yarn", "test"]
    env:
      - NODE_ENV=development
      - JOB_APPLICATION_KIND=testKind
      - USER_FIELD_NAME=userId

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Upload docker image to gcr.io"
    args: ["builds", "submit", "--config=docker_build.yaml",
           "--project" ,"global-application-example",
           "--substitutions", "_IMAGE_URL=\"gcr.io/global-application-example/global-apps-backend\",_DEPLOY_ENV=\"production\""]

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy Cloud Run Service"
    args: ["run", "deploy", "global-apps-backend", "--project", "global-application-example", "--region", "europe-west1", "--no-allow-unauthenticated", "--image", "gcr.io/global-application-example/global-apps-backend", "--platform", "managed"]
    env:
      - NODE_ENV=production
